In [1]:
import pandas as pd
import gc

In [2]:
#读入整个的embedding
creative_id_embedding = pd.read_csv('output/model/creative_id_embedding.csv')
creative_id_embedding

,creative_id,creative_id_embe_0,creative_id_embe_1,creative_id_embe_2,creative_id_embe_3,creative_id_embe_4,creative_id_embe_5,creative_id_embe_6,creative_id_embe_7,creative_id_embe_8,...,creative_id_embe_22,creative_id_embe_23,creative_id_embe_24,creative_id_embe_25,creative_id_embe_26,creative_id_embe_27,creative_id_embe_28,creative_id_embe_29,creative_id_embe_30,creative_id_embe_31
0,1,-0.537792,-0.343738,-0.169357,0.170321,-0.142634,-0.133415,0.015727,0.575709,-0.714908,...,-0.395647,0.067353,0.055399,0.074493,-0.036078,0.190803,0.714070,-0.100935,0.309329,0.063770
1,4,-0.525975,-0.368707,-0.289037,-0.434968,0.039553,-0.355471,-0.223031,0.464887,-0.182532,...,-0.835788,-0.075186,0.597538,0.056204,0.172193,0.052432,0.639376,-0.063182,0.817930,-0.240091
2,7,-0.077517,-0.140333,-0.011366,-0.080992,-0.283651,-0.032912,-0.273827,0.224146,-0.195711,...,-0.008073,0.029026,-0.045505,0.152764,-0.091590,-0.029852,0.127660,0.134912,0.115477,0.092430
3,10,-0.112068,-0.231497,-0.043593,-0.166035,-0.165059,-0.094334,-0.007987,0.236783,-0.223286,...,-0.071596,-0.043822,0.119022,0.052398,0.081226,0.157128,0.278553,-0.083885,0.322027,0.105955
4,13,-0.245735,-0.481754,0.052759,-0.122637,-0.141151,-0.118338,-0.158126,0.259479,-0.034940,...,-0.441856,-0.191594,0.339228,-0.044013,0.141239,0.283528,0.169891,-0.121109,0.240923,-0.135798
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2086581,4445710,-0.173163,-0.087752,-0.091049,-0.142106,-0.060819,-0.118301,0.030556,0.099103,-0.108970,...,-0.163997,0.010826,0.143995,-0.022708,-0.038149,0.012862,0.114340,-0.087390,0.194263,0.004597
2086582,4445711,-0.240102,-0.245562,-0.012533,-0.109751,-0.185693,-0.186433,0.019425,0.077360,-0.092199,...,-0.265054,-0.122758,0.133444,0.038254,0.119017,0.043823,0.130895,0.005913,0.025594,-0.061541
2086583,4445715,-0.101917,-0.142415,-0.086243,-0.042997,-0.112699,-0.129123,-0.068477,0.088054,0.048495,...,-0.095513,-0.085330,0.184931,0.029114,-0.074619,0.087402,0.137976,-0.162941,0.240736,0.019241
2086584,4445718,-0.191890,-0.157027,-0.046568,-0.051968,-0.124664,-0.124049,-0.030051,0.041827,-0.049231,...,-0.142483,-0.072065,0.168712,-0.041088,-0.097093,0.046425,0.174572,-0.073851,0.151137,0.054175
2086585,4445719,-0.116226,-0.181461,-0.045992,-0.051076,-0.103050,-0.065150,-0.021088,0.022904,-0.066603,...,-0.136009,-0.146907,0.134138,-0.038167,-0.059773,0.001099,0.108819,-0.090383,0.075723,0.017936

训练集

In [3]:
train_click_log = pd.read_csv('data/train_preliminary/click_log.csv')
train_click_log 
# test_click_log = pd.read_csv('data/test/click_log.csv')
# train_test_click_log = train_click_log.append(test_click_log)
# train_test_features = train_test_click_log[['user_id', 'creative_id']]
# train_test_features

          time  user_id  creative_id  click_times
0            9    30920       567330            1
1           65    30920      3072255            1
2           56    30920      2361327            1
3            6   309204       325532            1
4           59   309204      2746730            1
...        ...      ...          ...          ...
30082766     6    30920       228129            1
30082767    57    30920      2361397            1
30082768    26    30920       629802            1
30082769    86    30920      2713031            1
30082770    25    30920       629802            1

[30082771 rows x 4 columns]

In [6]:
train_features = train_click_log[['user_id', 'creative_id']]
del train_click_log
gc.collect()
train_features

          user_id  creative_id
0           30920       567330
1           30920      3072255
2           30920      2361327
3          309204       325532
4          309204      2746730
...           ...          ...
30082766    30920       228129
30082767    30920      2361397
30082768    30920       629802
30082769    30920      2713031
30082770    30920       629802

[30082771 rows x 2 columns]

In [7]:
train_id = train_features[['user_id']].drop_duplicates()
train_id

          user_id
0           30920
3          309204
28         309208
39          30921
52         309215
...           ...
30082472    30919
30082562   309192
30082613   309194
30082623   309197
30082639   309198

[900000 rows x 1 columns]

In [8]:
train_creative_id_embedding = pd.merge(train_features, creative_id_embedding, on='creative_id', how='left')
train_creative_id_embedding

,user_id,creative_id,creative_id_embe_0,creative_id_embe_1,creative_id_embe_2,creative_id_embe_3,creative_id_embe_4,creative_id_embe_5,creative_id_embe_6,creative_id_embe_7,...,creative_id_embe_22,creative_id_embe_23,creative_id_embe_24,creative_id_embe_25,creative_id_embe_26,creative_id_embe_27,creative_id_embe_28,creative_id_embe_29,creative_id_embe_30,creative_id_embe_31
0,30920,567330,-1.782609,-1.537899,-0.780065,0.491585,-0.550224,-1.070487,-0.586802,1.288426,...,-4.640288,-1.750510,4.007257,1.582147,1.535502,-0.110773,0.436095,-2.181622,0.866590,-1.777391
1,30920,3072255,-2.001559,3.691479,0.116128,-0.385789,-2.321904,-1.503856,-6.875677,0.317309,...,-0.273725,2.401443,-3.620612,-0.571777,1.628458,6.457458,-1.451168,-0.380044,5.098026,6.431285
2,30920,2361327,-3.759636,3.412679,-0.516845,-1.323732,-4.085909,-2.835023,-4.708904,-2.379167,...,-1.396061,2.132862,-4.222575,-2.679646,-1.560484,1.312825,-2.238295,1.463364,2.698371,6.271801
3,309204,325532,-0.272760,-0.357670,-0.079554,-0.224106,-0.118806,-0.027806,-0.041551,0.108541,...,-0.382541,-0.241179,0.279484,-0.081425,-0.095901,0.051589,0.093598,-0.094549,0.147813,-0.034702
4,309204,2746730,0.177951,-0.828602,0.029535,-0.498713,-0.087459,0.069312,0.332647,0.162248,...,-1.107889,-0.890322,-0.705347,0.324571,-0.650912,-0.590216,-0.372311,0.761130,-0.792024,-0.268926
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30082766,30920,228129,-10.794529,-2.598307,-0.875289,0.408210,1.440756,-3.176443,-0.105130,1.524676,...,-8.573648,1.484562,3.091336,3.041114,-0.469159,-0.420205,-5.342957,-3.279753,-3.804028,-1.554463
30082767,30920,2361397,-3.142921,7.682075,-1.615759,-1.116464,-4.570355,-3.993345,-5.232605,-2.004981,...,-0.734731,5.238952,-5.962598,-4.444032,-2.002913,2.765898,-2.625423,4.106539,3.195457,9.642706
30082768,30920,629802,-5.565780,8.543136,-7.615447,-2.793439,-3.250869,-3.845956,0.192927,0.379692,...,0.421232,6.921428,-1.312834,-2.362345,3.966226,0.432663,-4.366095,-5.168790,-0.499559,4.431464
30082769,30920,2713031,-1.768263,2.191330,-0.623171,1.565256,-5.770161,1.924781,-6.054282,4.291631,...,3.671960,6.130865,-2.708955,6.116122,0.702345,2.234132,4.213202,1.760830,0.019966,-0.936496
30082770,30920,629802,-5.565780,8.543136,-7.615447,-2.793439,-3.250869,-3.845956,0.192927,0.379692,...,0.421232,6.921428,-1.312834,-2.362345,3.966226,0.432663,-4.366095,-5.168790,-0.499559,4.431464

In [10]:
def extract_feat(df_, key, name, L, train_id):
    for i in range(L):
        t = df_.groupby(key).aggregate({'{0}_embe_{1}'.format(name, i):['mean','min','max']}).reset_index()
        t.columns = ['_'.join(j).strip('_') for j in t.columns.values]
        train_id = pd.merge(train_id, t, on=key, how='left')
        del t 
        gc.collect()
    return train_id

In [11]:
train_creative_id_embedding_df= extract_feat(train_creative_id_embedding, 'user_id', 'creative_id', 32, train_id)

In [12]:
train_creative_id_embedding_df

,user_id,creative_id_embe_0_mean,creative_id_embe_0_min,creative_id_embe_0_max,creative_id_embe_1_mean,creative_id_embe_1_min,creative_id_embe_1_max,creative_id_embe_2_mean,creative_id_embe_2_min,creative_id_embe_2_max,...,creative_id_embe_28_max,creative_id_embe_29_mean,creative_id_embe_29_min,creative_id_embe_29_max,creative_id_embe_30_mean,creative_id_embe_30_min,creative_id_embe_30_max,creative_id_embe_31_mean,creative_id_embe_31_min,creative_id_embe_31_max
0,30920,-1.998097,-10.794529,6.969045,1.799544,-6.228496,8.543136,-0.934299,-7.615447,5.654773,...,4.619198,0.845378,-5.625792,7.422933,0.599245,-3.804028,5.098026,2.479796,-4.375948,9.642706
1,309204,-1.287592,-3.949012,0.177951,-1.364933,-5.915030,2.352590,0.358347,-1.049812,2.154114,...,0.093598,0.522261,-1.610652,4.962090,-0.355537,-3.360490,1.046331,0.074650,-1.759645,3.372108
2,309208,-1.851677,-6.574865,1.635832,1.004908,-1.881781,6.699037,-1.467674,-4.632150,1.315974,...,9.032825,-0.999880,-3.055694,0.883220,2.416501,-1.213108,7.595332,-0.896246,-4.992641,2.711893
3,30921,-0.582027,-4.508259,2.806972,-0.353743,-5.650924,3.891286,0.564811,-5.063116,6.867293,...,3.723746,1.718167,-3.475857,8.014318,1.945667,-0.052157,3.618647,1.288883,-2.889746,6.176868
4,309215,-2.835513,-13.038307,5.425632,-1.510671,-6.106002,1.000905,-0.025756,-3.637015,4.177258,...,3.081962,0.687276,-5.054908,9.410289,-0.179415,-2.181192,2.259964,0.185727,-1.997094,3.378654
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
899995,30919,-0.072199,-5.651601,4.940872,-0.806176,-6.285697,7.817696,-2.468456,-11.476027,3.525708,...,7.064113,0.313918,-8.530261,6.094591,1.930530,-3.661117,7.971159,2.163167,-3.996461,10.013453
899996,309192,-0.492873,-6.396584,2.231535,0.115721,-3.735058,6.154131,1.303255,-7.428153,7.045382,...,6.399645,-1.981242,-9.434589,6.609170,1.539884,-1.530910,6.259771,0.260945,-1.848052,6.922099
899997,309194,-1.094455,-3.621879,1.254473,1.541164,-2.972023,8.598171,-0.177468,-3.926359,4.213249,...,2.206203,-1.710749,-5.748300,4.106539,2.607045,-0.175129,9.210293,2.696946,-1.585562,9.642706
899998,309197,-0.409176,-5.120891,2.244131,1.145689,-4.302811,8.701427,0.489285,-4.618417,6.616661,...,5.965206,1.558525,-1.334754,8.361802,1.983523,0.059458,4.402968,2.099910,-2.243819,5.921796
899999,309198,0.532610,-5.403923,7.195252,1.219640,-1.725814,7.552307,-0.517210,-9.233757,6.412634,...,10.615280,-0.514108,-5.381501,4.279218,1.608077,-2.691033,8.844506,-0.674758,-6.651448,4.319139

In [13]:
train_creative_id_embedding_df.to_csv('output/features/train/creative_id_embedding_df.csv', index=False)

In [14]:
del train_features, train_id, train_creative_id_embedding, train_creative_id_embedding_df
gc.collect()

0

测试集

In [3]:
test_click_log = pd.read_csv('data/test/click_log.csv')
test_click_log

          time  user_id  creative_id  click_times
0           20  3131989       645764            1
1           20  3131989      1027422            1
2           20  3131989      1106443            1
3           20  3131989       629802            1
4           59  3131989      2839769            1
...        ...      ...          ...          ...
33585507    16  3131989       585914            1
33585508    13  3131989       749134            1
33585509    12  3131989       589027            1
33585510    61  3131989      2404831            1
33585511    14  3131989       665822            1

[33585512 rows x 4 columns]

In [4]:
test_features = test_click_log[['user_id', 'creative_id']]
del test_click_log
gc.collect()
test_features

          user_id  creative_id
0         3131989       645764
1         3131989      1027422
2         3131989      1106443
3         3131989       629802
4         3131989      2839769
...           ...          ...
33585507  3131989       585914
33585508  3131989       749134
33585509  3131989       589027
33585510  3131989      2404831
33585511  3131989       665822

[33585512 rows x 2 columns]

In [5]:
test_id = test_features[['user_id']].drop_duplicates()
test_id

          user_id
0         3131989
11        3131990
52        3131994
65        3131995
82        3132000
...           ...
33585384  3131979
33585421  3131983
33585431  3131984
33585456  3131987
33585471  3131988

[1000000 rows x 1 columns]

In [6]:
test_creative_id_embedding = pd.merge(test_features, creative_id_embedding, on='creative_id', how='left')
test_creative_id_embedding

,user_id,creative_id,creative_id_embe_0,creative_id_embe_1,creative_id_embe_2,creative_id_embe_3,creative_id_embe_4,creative_id_embe_5,creative_id_embe_6,creative_id_embe_7,...,creative_id_embe_22,creative_id_embe_23,creative_id_embe_24,creative_id_embe_25,creative_id_embe_26,creative_id_embe_27,creative_id_embe_28,creative_id_embe_29,creative_id_embe_30,creative_id_embe_31
0,3131989,645764,-2.032530,-1.170117,-1.130265,-1.771715,-3.637366,-1.390657,0.335652,0.852179,...,-2.253556,-0.682963,2.017145,-2.096451,1.272262,2.612838,-4.896392,-4.440090,3.990225,3.876199
1,3131989,1027422,-1.365524,0.182064,-1.043593,-1.066528,-1.851783,-0.747693,-0.753458,1.376492,...,-1.931561,0.949289,1.525766,-1.199178,1.138451,1.278637,-2.431564,-2.958792,3.106062,2.619765
2,3131989,1106443,-0.192768,-0.055015,-0.147054,0.094494,-0.112243,-0.211204,-0.003565,0.149150,...,-0.093664,0.035899,0.024886,-0.017855,-0.001120,0.125264,-0.373465,-0.354888,0.369722,0.340964
3,3131989,629802,-5.565780,8.543136,-7.615447,-2.793439,-3.250869,-3.845956,0.192927,0.379692,...,0.421232,6.921428,-1.312834,-2.362345,3.966226,0.432663,-4.366095,-5.168790,-0.499559,4.431464
4,3131989,2839769,-0.071458,-0.251518,-0.107014,-0.278249,-0.178268,-0.220069,-0.152948,0.301697,...,-0.148451,0.248045,0.064881,-0.077118,-0.081715,0.342822,0.196679,-0.001370,0.291379,0.175142
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33585507,3131989,585914,-1.672336,-0.802919,-1.548668,0.247733,-2.035136,-0.878295,-0.060541,2.544211,...,-4.059803,0.954648,2.572759,-2.675700,1.919663,2.244580,-4.455463,-4.317420,4.185862,3.238381
33585508,3131989,749134,-1.175052,-0.688911,-0.781338,-0.368040,-1.190565,-0.723043,-0.256924,0.979153,...,-1.830067,0.281501,0.882500,-1.057918,-0.222761,1.019235,-2.031717,-2.816777,2.118517,1.601417
33585509,3131989,589027,-1.162470,0.020133,-0.146028,-0.814905,-0.669958,-0.375455,-0.112326,0.990278,...,-1.197350,0.759056,0.747961,-0.523558,0.875672,0.437456,-0.998180,-2.011087,0.979204,0.981733
33585510,3131989,2404831,-0.165170,-0.054598,-0.174323,-0.356255,-0.116947,-0.101486,0.021159,0.225767,...,0.068944,0.220984,-0.181211,-0.010532,-0.521483,-0.012095,0.391615,-0.107759,0.452129,0.352113
33585511,3131989,665822,-0.568040,-0.769384,-0.064977,-0.471988,-0.349200,-0.773146,0.153388,0.486809,...,-0.846503,-0.230559,0.416597,-0.397496,-0.245826,0.413642,-0.297583,-0.505765,0.707296,0.133367

In [7]:
def extract_feat(df_, key, name, L, train_id):
    for i in range(L):
        t = df_.groupby(key).aggregate({'{0}_embe_{1}'.format(name, i):['mean','min','max']}).reset_index()
        t.columns = ['_'.join(j).strip('_') for j in t.columns.values]
        train_id = pd.merge(train_id, t, on=key, how='left')
        del t 
        gc.collect()
    return train_id

In [8]:
test_creative_id_embedding_df = extract_feat(test_creative_id_embedding, 'user_id', 'creative_id', 32, test_id)
test_creative_id_embedding_df

,user_id,creative_id_embe_0_mean,creative_id_embe_0_min,creative_id_embe_0_max,creative_id_embe_1_mean,creative_id_embe_1_min,creative_id_embe_1_max,creative_id_embe_2_mean,creative_id_embe_2_min,creative_id_embe_2_max,...,creative_id_embe_28_max,creative_id_embe_29_mean,creative_id_embe_29_min,creative_id_embe_29_max,creative_id_embe_30_mean,creative_id_embe_30_min,creative_id_embe_30_max,creative_id_embe_31_mean,creative_id_embe_31_min,creative_id_embe_31_max
0,3131989,-1.610615,-5.565780,0.457868,-0.121777,-5.563427,8.543136,-1.408502,-7.615447,0.220511,...,0.391615,-2.574160,-5.922167,1.499623,2.234828,-0.499559,5.298047,1.731173,0.133367,4.589709
1,3131990,0.984589,-4.740649,4.928447,-1.068174,-7.272844,3.723213,0.348213,-4.821023,6.014134,...,6.251326,1.887970,-3.639199,7.731938,3.645505,-0.487317,12.526638,0.933395,-3.190908,4.777088
2,3131994,0.099161,-0.334279,1.429543,-0.151096,-1.167434,0.685617,-0.366257,-2.704952,1.800229,...,6.629500,-1.097067,-5.700393,-0.090909,1.552226,0.067300,7.754210,-0.192019,-2.617232,0.468096
3,3131995,-2.019656,-5.343575,1.953773,2.246829,-0.641369,5.495167,-1.027861,-8.339540,4.645638,...,3.210536,2.954364,-1.499885,8.680232,4.177405,-1.136900,9.672639,1.010773,-2.924395,7.746728
4,3132000,-0.583554,-4.591617,4.946285,1.569049,-3.749815,8.732292,-1.816888,-4.960374,3.900315,...,6.218210,2.622151,-3.639199,8.262675,2.321195,-3.808590,9.689359,0.554199,-3.516505,4.593669
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,3131979,-0.609154,-3.547217,3.865804,-0.894415,-7.680862,6.839928,-1.004994,-6.836400,3.253717,...,4.513284,0.276150,-4.392698,5.896319,0.449475,-2.302316,5.689931,0.982851,-1.558606,6.234326
999996,3131983,0.743641,-2.666733,5.170954,0.205330,-3.630289,4.525804,0.123004,-2.650134,1.754169,...,4.943682,-0.227278,-1.982078,1.707849,1.954145,-1.642099,6.425272,0.849500,-2.057543,4.900414
999997,3131984,-1.986724,-7.649400,1.749969,-0.315870,-5.663124,5.063706,-1.004628,-6.577161,1.379733,...,4.491964,-0.129638,-4.910450,5.365379,0.777931,-2.530640,4.149045,2.454216,-0.287703,8.940969
999998,3131987,0.336325,-1.669199,2.970039,-1.390888,-3.886888,2.534978,0.372990,-3.847244,5.091736,...,3.592960,1.067436,-0.833431,4.855446,-0.551974,-2.312248,0.996236,-1.150526,-2.649251,2.022489
999999,3131988,-0.724096,-5.460486,6.969045,2.449260,-0.519017,7.682075,-0.623961,-4.333015,3.803094,...,0.980503,-0.186462,-3.986632,7.422933,2.333642,0.147380,6.666282,3.404664,-0.817800,9.642706

In [9]:
test_creative_id_embedding_df.to_csv('output/features/test/creative_id_embedding_df.csv', index=False)